name: wrlc8
recipe: drupal8
config:
  webroot: web
  database: mariadb:10.1
proxy:
  appserver:
    - wrlc8.lndo.site  # www.wrlc.org
    - hq.wrlc8.lndo.site  # www.hq.wrlc.org
    - libraries.wrlc8.lndo.site  # www.libraries.wrlc.org
services:
  # wrlc.org D7 database for migration
  wrlc7:
    type: mariadb:10.1
    portforward: true
  # www.hq.wrlc.org database
  hq:
    type: mariadb:10.1
    portforward: true
  # www.hq.wrlc.org D7 database for migration
  hq7:
    type: mariadb:10.1
    portforward: true
  # www.libraries.wrlc.org database
  libraries:
    type: mariadb:10.1
    portforward: true
  # www.libraries.wrlc.org D7 database for migration
  libraries7:
    type: mariadb:10.1
    portforward: true
