<?php

/**
 * @file
 * Contains skills_custom_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function skills_custom_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the skills_custom_module module.
    case 'help.page.skills_custom_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom functions for Skills site') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_form_alter().
 */
function skills_custom_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_form') {
    ksm($form);
  }
}
